### PR TITLE
ogen: add Generate() func to enable users to use ogen as a package

### PR DESCRIPTION
**Pull request by masseelch**
WDYT @ernado

### CODE REVIEW

**Comment by ernado** [comment]
Looks good in general, thank you ⚡ 

Please make pipeline green so I can merge this.

**Comment by masseelch** [comment]
Do you prefer to move spec into its own package or have a package `pkg` where I put the `Generate`? (Currently there is an import cycle, I wanted to propose the general idea first).

**Comment by ernado** [comment]
I prefer not to use `pkg` overall.

Can we just export gen package?
Let me think a bit

**Comment by masseelch** [comment]
> I prefer not to use `pkg` overall.

Me neither. A lot people do though. Exporting `gen` is possible too. In that case the `Generate()` function might not even be needed.

**Comment by masseelch** [comment]
@ernado Any news on this? Do we want to export `gen` package?

**Comment by ernado** [comment]
Yes, we can do it.

**Comment by masseelch** [comment]
I have a working branch already. If this is okay, I can PR it. https://github.com/masseelch/ogen/tree/feat/exported-gen

**Comment by ernado** [comment]
Great! Go ahead with PR @masseelch

**Comment by masseelch** [comment]
Fixed in #86

**Pull request closed without merging**
