### PR TITLE
Added option to skip default response

### PR DESCRIPTION
**Pull request by ReallyLiri**
In cases where api defines default generic response, it makes for much more boilerplate code of checking which instance type the response interface is.
Sometimes its easier to handle as an `err` rather than a case check per response.
i.e `PetGet(ctx context.Context, params PetGetParams) (PetGetRes, error)`, `PetGetRes` which might be a `Pet` or might be a generic error `PetGetDefStatusCode`

### CODE REVIEW

**Comment by ernado** [comment]
Looks very similar to [conventient errors](https://ogen.dev/docs/concepts/convenient_errors).

**Comment by ReallyLiri** [comment]
> Looks very similar to [conventient errors](https://ogen.dev/docs/concepts/convenient_errors).

Indeed, but in my use case only majority of the operations have this default error, while others don't for various reasons.

I can understand if ogen doesn't wish to make the options so opinionated as to support only this partial convenient errors case.

**Comment by ernado** [comment]
We will take a look into this feature, thank you for your PR :heart: 

Currently we (me and tdakkota) are slightly out of capacity, so it can take some time.

Probably we should consider moving to `yaml`-based configuration soon :D

**Comment by ReallyLiri** [comment]
Unfortunately I don't have the time to invest in getting this PR "to code", if anyone wants to pick it up, please do.

**Pull request closed without merging**
